CATEGORY_CHOICES = [
        ('adguard', 'AdGuard Products'),
        ('adobe', 'Adobe Products'),
        ('aida64', 'AIDA64 Products'),
        ('aiseesoft', 'Aiseesoft Products'),
        ('aomei', 'AOMEI Products'),
        ('ashampoo', 'Ashampoo Products'),
        ('autodesk', 'Autodesk Products'),
        ('bitdefender', 'Bitdefender Products'),
        ('ccleaner', 'CCleaner Products'),
        ('corel', 'Corel Products'),
        ('drivermagician', 'DriverMagician Products'),
        ('easeus', 'EaseUS Products'),
        ('eset', 'ESET Products'),
        ('glarysoft', 'Glarysoft Products'),
        ('kaspersky', 'Kaspersky Products'),
        ('macos', 'MacOs Software'),
        ('office2013', 'Microsoft Office 2013 Products'),
        ('office2016', 'Microsoft Office 2016 Products'),
        ('office2019', 'Microsoft Office 2019 Products'),
        ('office2021', 'Microsoft Office 2021 Products'),
        ('office2024', 'Microsoft Office 2024 Products'),
        ('office365', 'Microsoft Office 365 Products'),
        ('server', 'Microsoft Server Products'),
        ('sql', 'Microsoft SQL Server Products'),
        ('visualstudio', 'Microsoft Visual Studio Products'),
        ('windows10', 'Microsoft Windows 10 Products'),
        ('windows11', 'Microsoft Windows 11 Products'),
        ('windows7', 'Microsoft Windows 7 Products'),
        ('windows8', 'Microsoft Windows 8 Products'),
        ('mindmanager', 'MindManager Products'),
        ('nitro', 'Nitro Products'),
        ('spotify', 'Spotify Subscription'),
        ('subscription', 'Subscription and Credits'),
        ('symantec', 'Symantec Products'),
        ('vmware', 'VMware Products'),
        ('vpn', 'VPN Products'),
    ]