# Generated by Django 5.1.4 on 2024-12-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digikeyoutlet', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital_file',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product_images/default.jpg', upload_to='product_images/'),
        ),
    ]
