# Generated by Django 5.1.4 on 2024-12-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digikeyoutlet', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
