# Generated by Django 5.1.4 on 2024-12-19 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digikeyoutlet', '0007_cartitem_selected_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('is_sold', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digikeyoutlet.product')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='purchased_keys',
            field=models.ManyToManyField(to='digikeyoutlet.productkey'),
        ),
    ]
