# Generated by Django 5.1.4 on 2024-12-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digikeyoutlet', '0008_productkey_userprofile_purchased_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='purchased_keys',
            field=models.ManyToManyField(related_name='user_profiles', to='digikeyoutlet.productkey'),
        ),
    ]
