# Generated by Django 5.1.4 on 2024-12-19 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digikeyoutlet', '0009_alter_userprofile_purchased_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productkey',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='digikeyoutlet.product'),
        ),
    ]
