# Generated by Django 5.1.4 on 2024-12-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digikeyoutlet', '0010_alter_productkey_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productkey',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
