# Generated by Django 5.1.4 on 2024-12-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digikeyoutlet', '0011_alter_productkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('windows', 'Windows'), ('office', 'Office'), ('photoshop', 'Photoshop')], default='windows', max_length=50),
        ),
        migrations.AlterField(
            model_name='productkey',
            name='key',
            field=models.CharField(max_length=255),
        ),
    ]
